/* tslint:disable */
/* eslint-disable */
/**
 * Finance Dashboard API
 * Finance Data Processing & Access Control Backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateTransactionDto } from '../models';
// @ts-ignore
import type { UpdateTransactionDto } from '../models';
/**
 * TransactionsApi - axios parameter creator
 */
export const TransactionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateTransactionDto} createTransactionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsControllerCreate: async (createTransactionDto: CreateTransactionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createTransactionDto' is not null or undefined
            assertParamExists('transactionsControllerCreate', 'createTransactionDto', createTransactionDto)
            const localVarPath = `/api/v1/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication x-user-id required
            await setApiKeyToObject(localVarHeaderParameter, "x-user-id", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTransactionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {TransactionsControllerFindAllTypeEnum} [type] 
         * @param {string} [category] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {string} [page] 
         * @param {string} [limit] 
         * @param {TransactionsControllerFindAllSortByEnum} [sortBy] 
         * @param {TransactionsControllerFindAllOrderEnum} [order] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsControllerFindAll: async (type?: TransactionsControllerFindAllTypeEnum, category?: string, from?: string, to?: string, page?: string, limit?: string, sortBy?: TransactionsControllerFindAllSortByEnum, order?: TransactionsControllerFindAllOrderEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication x-user-id required
            await setApiKeyToObject(localVarHeaderParameter, "x-user-id", configuration)

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('transactionsControllerFindOne', 'id', id)
            const localVarPath = `/api/v1/transactions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication x-user-id required
            await setApiKeyToObject(localVarHeaderParameter, "x-user-id", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('transactionsControllerRemove', 'id', id)
            const localVarPath = `/api/v1/transactions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication x-user-id required
            await setApiKeyToObject(localVarHeaderParameter, "x-user-id", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateTransactionDto} updateTransactionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsControllerUpdate: async (id: string, updateTransactionDto: UpdateTransactionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('transactionsControllerUpdate', 'id', id)
            // verify required parameter 'updateTransactionDto' is not null or undefined
            assertParamExists('transactionsControllerUpdate', 'updateTransactionDto', updateTransactionDto)
            const localVarPath = `/api/v1/transactions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication x-user-id required
            await setApiKeyToObject(localVarHeaderParameter, "x-user-id", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateTransactionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionsApi - functional programming interface
 */
export const TransactionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransactionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateTransactionDto} createTransactionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionsControllerCreate(createTransactionDto: CreateTransactionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transactionsControllerCreate(createTransactionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.transactionsControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {TransactionsControllerFindAllTypeEnum} [type] 
         * @param {string} [category] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {string} [page] 
         * @param {string} [limit] 
         * @param {TransactionsControllerFindAllSortByEnum} [sortBy] 
         * @param {TransactionsControllerFindAllOrderEnum} [order] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionsControllerFindAll(type?: TransactionsControllerFindAllTypeEnum, category?: string, from?: string, to?: string, page?: string, limit?: string, sortBy?: TransactionsControllerFindAllSortByEnum, order?: TransactionsControllerFindAllOrderEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transactionsControllerFindAll(type, category, from, to, page, limit, sortBy, order, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.transactionsControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionsControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transactionsControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.transactionsControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionsControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transactionsControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.transactionsControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateTransactionDto} updateTransactionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionsControllerUpdate(id: string, updateTransactionDto: UpdateTransactionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transactionsControllerUpdate(id, updateTransactionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.transactionsControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TransactionsApi - factory interface
 */
export const TransactionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransactionsApiFp(configuration)
    return {
        /**
         * 
         * @param {CreateTransactionDto} createTransactionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsControllerCreate(createTransactionDto: CreateTransactionDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.transactionsControllerCreate(createTransactionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TransactionsControllerFindAllTypeEnum} [type] 
         * @param {string} [category] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {string} [page] 
         * @param {string} [limit] 
         * @param {TransactionsControllerFindAllSortByEnum} [sortBy] 
         * @param {TransactionsControllerFindAllOrderEnum} [order] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsControllerFindAll(type?: TransactionsControllerFindAllTypeEnum, category?: string, from?: string, to?: string, page?: string, limit?: string, sortBy?: TransactionsControllerFindAllSortByEnum, order?: TransactionsControllerFindAllOrderEnum, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.transactionsControllerFindAll(type, category, from, to, page, limit, sortBy, order, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.transactionsControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsControllerRemove(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.transactionsControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateTransactionDto} updateTransactionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsControllerUpdate(id: string, updateTransactionDto: UpdateTransactionDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.transactionsControllerUpdate(id, updateTransactionDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TransactionsApi - object-oriented interface
 */
export class TransactionsApi extends BaseAPI {
    /**
     * 
     * @param {CreateTransactionDto} createTransactionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public transactionsControllerCreate(createTransactionDto: CreateTransactionDto, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).transactionsControllerCreate(createTransactionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TransactionsControllerFindAllTypeEnum} [type] 
     * @param {string} [category] 
     * @param {string} [from] 
     * @param {string} [to] 
     * @param {string} [page] 
     * @param {string} [limit] 
     * @param {TransactionsControllerFindAllSortByEnum} [sortBy] 
     * @param {TransactionsControllerFindAllOrderEnum} [order] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public transactionsControllerFindAll(type?: TransactionsControllerFindAllTypeEnum, category?: string, from?: string, to?: string, page?: string, limit?: string, sortBy?: TransactionsControllerFindAllSortByEnum, order?: TransactionsControllerFindAllOrderEnum, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).transactionsControllerFindAll(type, category, from, to, page, limit, sortBy, order, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public transactionsControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).transactionsControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public transactionsControllerRemove(id: string, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).transactionsControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {UpdateTransactionDto} updateTransactionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public transactionsControllerUpdate(id: string, updateTransactionDto: UpdateTransactionDto, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).transactionsControllerUpdate(id, updateTransactionDto, options).then((request) => request(this.axios, this.basePath));
    }
}

export const TransactionsControllerFindAllTypeEnum = {
    Income: 'INCOME',
    Expense: 'EXPENSE'
} as const;
export type TransactionsControllerFindAllTypeEnum = typeof TransactionsControllerFindAllTypeEnum[keyof typeof TransactionsControllerFindAllTypeEnum];
export const TransactionsControllerFindAllSortByEnum = {
    Date: 'date',
    Amount: 'amount',
    CreatedAt: 'createdAt'
} as const;
export type TransactionsControllerFindAllSortByEnum = typeof TransactionsControllerFindAllSortByEnum[keyof typeof TransactionsControllerFindAllSortByEnum];
export const TransactionsControllerFindAllOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type TransactionsControllerFindAllOrderEnum = typeof TransactionsControllerFindAllOrderEnum[keyof typeof TransactionsControllerFindAllOrderEnum];
