/* tslint:disable */
/* eslint-disable */
/**
 * Finance Dashboard API
 * Finance Data Processing & Access Control Backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AssignRoleDto {
    'role': AssignRoleDtoRoleEnum;
}

export const AssignRoleDtoRoleEnum = {
    Viewer: 'VIEWER',
    Analyst: 'ANALYST',
    Admin: 'ADMIN'
} as const;

export type AssignRoleDtoRoleEnum = typeof AssignRoleDtoRoleEnum[keyof typeof AssignRoleDtoRoleEnum];


