/* tslint:disable */
/* eslint-disable */
/**
 * Finance Dashboard API
 * Finance Data Processing & Access Control Backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateTransactionDto {
    /**
     * Amount in base currency unit
     */
    'amount'?: number;
    'type'?: UpdateTransactionDtoTypeEnum;
    'category'?: string;
    'date'?: string;
    'notes'?: string;
}

export const UpdateTransactionDtoTypeEnum = {
    Income: 'INCOME',
    Expense: 'EXPENSE'
} as const;

export type UpdateTransactionDtoTypeEnum = typeof UpdateTransactionDtoTypeEnum[keyof typeof UpdateTransactionDtoTypeEnum];


